server:
  port: 8085

spring:
  application:
    name: room-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gamematch_room}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:p1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true